"""add_risk_score_fields

Revision ID: 3f743b4d870d
Revises: b26ec8e8e360
Create Date: 2026-04-03 22:20:49.106004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f743b4d870d'
down_revision: Union[str, Sequence[str], None] = 'b26ec8e8e360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrower_profiles', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('borrower_profiles', sa.Column('risk_level', sa.String(20), nullable=True))
    op.add_column('borrower_profiles', sa.Column('last_risk_calculation', sa.DateTime(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrower_profiles', 'risk_score')
    op.drop_column('borrower_profiles', 'risk_level')
    op.drop_column('borrower_profiles', 'last_risk_calculation')