"""schema updates: decimal fields, audit columns, cleanup

Revision ID: ac171b455c35
Revises: a540995604b1
Create Date: 2026-03-21 18:49:45.418836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac171b455c35'
down_revision: Union[str, Sequence[str], None] = 'a540995604b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('addresses', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'addresses', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'addresses', 'users', ['updated_by'], ['id'])
    op.add_column('bank_accounts', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('bank_accounts', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bank_accounts', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'bank_accounts', 'users', ['updated_by'], ['id'])
    op.add_column('borrower_profiles', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('borrower_profiles', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('borrower_profiles', 'monthly_income',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'borrower_profiles', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'borrower_profiles', 'users', ['updated_by'], ['id'])
    op.drop_column('borrower_profiles', 'preferred_tenure_months')
    op.drop_column('borrower_profiles', 'total_existing_liabilities')
    op.drop_column('borrower_profiles', 'preferred_max_interest_rate')
    op.drop_column('borrower_profiles', 'credit_score')
    op.drop_column('borrower_profiles', 'preferred_min_amount')
    op.drop_column('borrower_profiles', 'existing_loan_count')
    op.drop_column('borrower_profiles', 'preferred_max_amount')
    op.add_column('lender_profiles', sa.Column('profile_name', sa.String(length=100), nullable=True))
    op.add_column('lender_profiles', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('lender_profiles', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('lender_profiles', 'available_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('lender_profiles', 'total_lent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'lender_profiles', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'lender_profiles', 'users', ['updated_by'], ['id'])
    op.drop_column('lender_profiles', 'default_min_tenure')
    op.drop_column('lender_profiles', 'default_interest_rate')
    op.drop_column('lender_profiles', 'default_min_amount')
    op.drop_column('lender_profiles', 'business_name')
    op.drop_column('lender_profiles', 'default_max_amount')
    op.drop_column('lender_profiles', 'default_max_tenure')
    op.add_column('loan_applications', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('loan_applications', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('loan_applications', 'requested_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'loan_applications', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'loan_applications', 'users', ['updated_by'], ['id'])
    op.add_column('loan_offers', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('loan_offers', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('loan_offers', 'min_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('loan_offers', 'max_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('loan_offers', 'interest_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'loan_offers', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'loan_offers', 'users', ['updated_by'], ['id'])
    op.add_column('loan_products', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('loan_products', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'loan_products', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'loan_products', 'users', ['created_by'], ['id'])
    op.add_column('user_profile', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('user_profile', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user_profile', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'user_profile', 'users', ['created_by'], ['id'])
    op.add_column('users', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'users', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.drop_column('user_profile', 'updated_by')
    op.drop_column('user_profile', 'created_by')
    op.drop_constraint(None, 'loan_products', type_='foreignkey')
    op.drop_constraint(None, 'loan_products', type_='foreignkey')
    op.drop_column('loan_products', 'updated_by')
    op.drop_column('loan_products', 'created_by')
    op.drop_constraint(None, 'loan_offers', type_='foreignkey')
    op.drop_constraint(None, 'loan_offers', type_='foreignkey')
    op.alter_column('loan_offers', 'interest_rate',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('loan_offers', 'max_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('loan_offers', 'min_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('loan_offers', 'updated_by')
    op.drop_column('loan_offers', 'created_by')
    op.drop_constraint(None, 'loan_applications', type_='foreignkey')
    op.drop_constraint(None, 'loan_applications', type_='foreignkey')
    op.alter_column('loan_applications', 'requested_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('loan_applications', 'updated_by')
    op.drop_column('loan_applications', 'created_by')
    op.add_column('lender_profiles', sa.Column('default_max_tenure', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lender_profiles', sa.Column('default_max_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('lender_profiles', sa.Column('business_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('lender_profiles', sa.Column('default_min_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('lender_profiles', sa.Column('default_interest_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('lender_profiles', sa.Column('default_min_tenure', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lender_profiles', type_='foreignkey')
    op.drop_constraint(None, 'lender_profiles', type_='foreignkey')
    op.alter_column('lender_profiles', 'total_lent',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('lender_profiles', 'available_balance',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('lender_profiles', 'updated_by')
    op.drop_column('lender_profiles', 'created_by')
    op.drop_column('lender_profiles', 'profile_name')
    op.add_column('borrower_profiles', sa.Column('preferred_max_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('borrower_profiles', sa.Column('existing_loan_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('borrower_profiles', sa.Column('preferred_min_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('borrower_profiles', sa.Column('credit_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('borrower_profiles', sa.Column('preferred_max_interest_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('borrower_profiles', sa.Column('total_existing_liabilities', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('borrower_profiles', sa.Column('preferred_tenure_months', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'borrower_profiles', type_='foreignkey')
    op.drop_constraint(None, 'borrower_profiles', type_='foreignkey')
    op.alter_column('borrower_profiles', 'monthly_income',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('borrower_profiles', 'updated_by')
    op.drop_column('borrower_profiles', 'created_by')
    op.drop_constraint(None, 'bank_accounts', type_='foreignkey')
    op.drop_constraint(None, 'bank_accounts', type_='foreignkey')
    op.drop_column('bank_accounts', 'updated_by')
    op.drop_column('bank_accounts', 'created_by')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'updated_by')
    op.drop_column('addresses', 'created_by')
    # ### end Alembic commands ###
