"""replace otp_code with otp_hash

Revision ID: b36582ded6e4
Revises: 394b86277d9a
Create Date: 2026-03-11 15:09:59.330643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b36582ded6e4'
down_revision: Union[str, Sequence[str], None] = '394b86277d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add column as NULLABLE first
    op.add_column('otp_verifications', sa.Column('otp_hash', sa.String(length=255), nullable=True))
    
    # Step 2: Migrate existing data (if any)
    op.execute("""
        UPDATE otp_verifications 
        SET otp_hash = otp_code 
        WHERE otp_code IS NOT NULL
    """)
    
    # Step 3: Now make it NOT NULL
    op.alter_column('otp_verifications', 'otp_hash', nullable=False)
    
    # Step 4: Update timestamps to timezone-aware
    op.alter_column('otp_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at AT TIME ZONE \'UTC\'',
               existing_nullable=True)
    
    op.alter_column('otp_verifications', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='expires_at AT TIME ZONE \'UTC\'',
               existing_nullable=False)
    
    # Step 5: Drop old column
    op.drop_column('otp_verifications', 'otp_code')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('otp_code', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.alter_column('otp_verifications', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('otp_verifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('otp_verifications', 'otp_hash')
    # ### end Alembic commands ###
