"""add missing tables

Revision ID: b39faa6222ca
Revises: 0e6528ad4315
Create Date: 2026-03-13 14:52:52.855683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39faa6222ca'
down_revision: Union[str, Sequence[str], None] = '0e6528ad4315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrower_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('employment_type', sa.Enum('SALARIED', 'SELF_EMPLOYED', 'BUSINESS', 'STUDENT', 'UNEMPLOYED', name='employmenttype'), nullable=False),
    sa.Column('monthly_income', sa.Float(), nullable=False),
    sa.Column('employer_name', sa.String(length=100), nullable=True),
    sa.Column('current_job_tenure_months', sa.Integer(), nullable=True),
    sa.Column('total_work_experience_years', sa.Integer(), nullable=True),
    sa.Column('preferred_min_amount', sa.Float(), nullable=True),
    sa.Column('preferred_max_amount', sa.Float(), nullable=True),
    sa.Column('preferred_tenure_months', sa.Integer(), nullable=True),
    sa.Column('preferred_max_interest_rate', sa.Float(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('existing_loan_count', sa.Integer(), nullable=True),
    sa.Column('total_existing_liabilities', sa.Float(), nullable=True),
    sa.Column('is_profile_complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('lender_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('available_balance', sa.Float(), nullable=False),
    sa.Column('total_lent', sa.Float(), nullable=False),
    sa.Column('default_min_amount', sa.Float(), nullable=True),
    sa.Column('default_max_amount', sa.Float(), nullable=True),
    sa.Column('default_min_tenure', sa.Integer(), nullable=True),
    sa.Column('default_max_tenure', sa.Integer(), nullable=True),
    sa.Column('default_interest_rate', sa.Float(), nullable=True),
    sa.Column('risk_appetite', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='riskappetite'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='lenderstatus'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('national_number', sa.String(length=15), nullable=False),
    sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', name='maritalstatus'), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('profile_completion_pct', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profile_email'), 'user_profile', ['email'], unique=True)
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_profile_id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.Enum('HOME', 'WORK', 'PERMANENT', name='addresstype'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('address_line1', sa.String(length=100), nullable=False),
    sa.Column('address_line2', sa.String(length=100), nullable=True),
    sa.Column('landmark', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    op.drop_index(op.f('ix_user_profile_email'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_table('lender_profiles')
    op.drop_table('borrower_profiles')
    # ### end Alembic commands ###
